<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('customers')->insert([
            [
                'customer_id' => 'C0001',
                'username' => 'kamonchanok_s',
                'password' => 'nan1234',
                'fullname' => 'กมลชนก แสงทอง',
                'phone' => '0812345671',
                'address' => '12/5 หมู่ 3 ต.บางพลี อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0234567890',
                'bust' => 84,
                'shoulder' => 36,
                'waist' => 64,
                'hips' => 90,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0002',
                'username' => 'thanya_ms',
                'password' => 'thanya99',
                'fullname' => 'ธัญญาลักษณ์ มีสุข',
                'phone' => '0823456782',
                'address' => '45 ถ.สุขุมวิท ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0345678901',
                'bust' => 86,
                'shoulder' => 37,
                'waist' => 66,
                'hips' => 92,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0003',
                'username' => 'benja_ik',
                'password' => 'benja2026',
                'fullname' => 'เบญจวรรณ อินทร์แก้ว',
                'phone' => '0834567893',
                'address' => '78 หมู่ 1 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0456789012',
                'bust' => 82,
                'shoulder' => 35,
                'waist' => 62,
                'hips' => 88,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0004',
                'username' => 'pawee_ch',
                'password' => 'paweena55',
                'fullname' => 'ปวีณา ชูเกียรติ',
                'phone' => '0845678904',
                'address' => '23/1 ต.สำโรงเหนือ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0567890123',
                'bust' => 88,
                'shoulder' => 38,
                'waist' => 68,
                'hips' => 94,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0005',
                'username' => 'pimchanok_r',
                'password' => 'pim2026',
                'fullname' => 'พิมพ์ชนก รุ่งเรือง',
                'phone' => '0856789015',
                'address' => '56 ถ.เทพารักษ์ ต.เทพารักษ์ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0678901234',
                'bust' => 85,
                'shoulder' => 36,
                'waist' => 65,
                'hips' => 91,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0006',
                'username' => 'rattana_bm',
                'password' => 'rattana77',
                'fullname' => 'รัตนาภรณ์ บุญมา',
                'phone' => '0867890126',
                'address' => '89 หมู่ 5 ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ 10570',
                'bank_account' => '0789012345',
                'bust' => 87,
                'shoulder' => 37,
                'waist' => 67,
                'hips' => 93,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0007',
                'username' => 'wannisa_sk',
                'password' => 'wannisa88',
                'fullname' => 'วรรณิษา ศรีสุข',
                'phone' => '0878901237',
                'address' => '34 ถ.ศรีนครินทร์ ต.สำโรง อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0890123456',
                'bust' => 83,
                'shoulder' => 35,
                'waist' => 63,
                'hips' => 89,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0008',
                'username' => 'sasithorn_k',
                'password' => 'sasi2026',
                'fullname' => 'ศศิธร แก้วมณี',
                'phone' => '0889012348',
                'address' => '67/2 หมู่ 4 ต.บางบ่อ อ.บางบ่อ จ.สมุทรปราการ 10560',
                'bank_account' => '0901234567',
                'bust' => 89,
                'shoulder' => 38,
                'waist' => 69,
                'hips' => 95,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0009',
                'username' => 'sunisa_pp',
                'password' => 'sunisa2026',
                'fullname' => 'สุนิสา พงษ์ไพร',
                'phone' => '0891234569',
                'address' => '90 ถ.เทพารักษ์ ต.บางปลา อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0812345678',
                'bust' => 84,
                'shoulder' => 36,
                'waist' => 64,
                'hips' => 90,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0010',
                'username' => 'orawan_td',
                'password' => 'orawan1234',
                'fullname' => 'อรวรรณ ทองดี',
                'phone' => '0898765432',
                'address' => '12 หมู่ 2 ต.บางปูใหม่ อ.เมือง จ.สมุทรปราการ 10280',
                'bank_account' => '0992345678',
                'bust' => 86,
                'shoulder' => 37,
                'waist' => 66,
                'hips' => 92,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}