<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash; //  1. เพิ่ม Facade Hash

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('customers')->insert([
            [
                'customer_id' => 'C0001',
                'username' => 'kamonchanok_s',
                'password' => Hash::make('nan1234'), //  2. ครอบด้วย Hash::make()
                'fullname' => 'กมลชนก แสงทอง',
                'phone' => '0812345671',
                'address' => '12/5 หมู่ 3 ต.บางพลี อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0234567890',
                'bust' => 84,
                'shoulder' => 36,
                'waist' => 64,
                'hips' => 90,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0002',
                'username' => 'thanya_ms',
                'password' => Hash::make('thanya99'),
                'fullname' => 'ธัญญาลักษณ์ มีสุข',
                'phone' => '0823456782',
                'address' => '45 ถ.สุขุมวิท ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0345678901',
                'bust' => 86,
                'shoulder' => 37,
                'waist' => 66,
                'hips' => 92,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0003',
                'username' => 'benja_ik',
                'password' => Hash::make('benja2026'),
                'fullname' => 'เบญจวรรณ อินทร์แก้ว',
                'phone' => '0834567893',
                'address' => '78 หมู่ 1 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0456789012',
                'bust' => 82,
                'shoulder' => 35,
                'waist' => 62,
                'hips' => 88,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0004',
                'username' => 'pawee_ch',
                'password' => Hash::make('paweena55'),
                'fullname' => 'ปวีณา ชูเกียรติ',
                'phone' => '0845678904',
                'address' => '23/1 ต.สำโรงเหนือ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0567890123',
                'bust' => 88,
                'shoulder' => 38,
                'waist' => 68,
                'hips' => 94,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0005',
                'username' => 'pimchanok_r',
                'password' => Hash::make('pim2026'),
                'fullname' => 'พิมพ์ชนก รุ่งเรือง',
                'phone' => '0856789015',
                'address' => '56 ถ.เทพารักษ์ ต.เทพารักษ์ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0678901234',
                'bust' => 85,
                'shoulder' => 36,
                'waist' => 65,
                'hips' => 91,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0006',
                'username' => 'rattana_bm',
                'password' => Hash::make('rattana77'),
                'fullname' => 'รัตนาภรณ์ บุญมา',
                'phone' => '0867890126',
                'address' => '89 หมู่ 5 ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ 10570',
                'bank_account' => '0789012345',
                'bust' => 87,
                'shoulder' => 37,
                'waist' => 67,
                'hips' => 93,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0007',
                'username' => 'wannisa_sk',
                'password' => Hash::make('wannisa88'),
                'fullname' => 'วรรณิษา ศรีสุข',
                'phone' => '0878901237',
                'address' => '34 ถ.ศรีนครินทร์ ต.สำโรง อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0890123456',
                'bust' => 83,
                'shoulder' => 35,
                'waist' => 63,
                'hips' => 89,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0008',
                'username' => 'sasithorn_k',
                'password' => Hash::make('sasi2026'),
                'fullname' => 'ศศิธร แก้วมณี',
                'phone' => '0889012348',
                'address' => '67/2 หมู่ 4 ต.บางบ่อ อ.บางบ่อ จ.สมุทรปราการ 10560',
                'bank_account' => '0901234567',
                'bust' => 89,
                'shoulder' => 38,
                'waist' => 69,
                'hips' => 95,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0009',
                'username' => 'sunisa_pp',
                'password' => Hash::make('sunisa2026'),
                'fullname' => 'สุนิสา พงษ์ไพร',
                'phone' => '0891234569',
                'address' => '90 ถ.เทพารักษ์ ต.บางปลา อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0812345678',
                'bust' => 84,
                'shoulder' => 36,
                'waist' => 64,
                'hips' => 90,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0010',
                'username' => 'orawan_td',
                'password' => Hash::make('orawan1234'),
                'fullname' => 'อรวรรณ ทองดี',
                'phone' => '0898765432',
                'address' => '12 หมู่ 2 ต.บางปูใหม่ อ.เมือง จ.สมุทรปราการ 10280',
                'bank_account' => '0992345678',
                'bust' => 86,
                'shoulder' => 37,
                'waist' => 66,
                'hips' => 92,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0011',
                'username' => 'chonticha_ws',
                'password' => Hash::make('chon2026'),
                'fullname' => 'ชลธิชา วงศ์สวัสดิ์',
                'phone' => '0902345671',
                'address' => '15/7 ถ.ศรีนครินทร์ ต.แพรกษา อ.เมือง จ.สมุทรปราการ 10280',
                'bank_account' => '0145678923',
                'bust' => 85,
                'shoulder' => 36,
                'waist' => 66,
                'hips' => 91,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0012',
                'username' => 'nattida_ps',
                'password' => Hash::make('natti1234'),
                'fullname' => 'ณัฐธิดา เพชรสุข',
                'phone' => '0913456782',
                'address' => '102 หมู่ 6 ต.บางโฉลง อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0256789034',
                'bust' => 83,
                'shoulder' => 35,
                'waist' => 62,
                'hips' => 90,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0013',
                'username' => 'areeya_jd',
                'password' => Hash::make('areeya88'),
                'fullname' => 'อารียา ใจดี',
                'phone' => '0924567893',
                'address' => '8/3 ถ.สายลวด ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ 10270',
                'bank_account' => '0367890145',
                'bust' => 87,
                'shoulder' => 37,
                'waist' => 68,
                'hips' => 93,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0014',
                'username' => 'kanyapak_sw',
                'password' => Hash::make('kanya2026'),
                'fullname' => 'กัญญาภัค สุวรรณรัตน์',
                'phone' => '0935678904',
                'address' => '41/9 ถ.สุขสวัสดิ์ ต.ตลาด อ.พระประแดง จ.สมุทรปราการ 10130',
                'bank_account' => '0478901256',
                'bust' => 90,
                'shoulder' => 39,
                'waist' => 70,
                'hips' => 96,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0015',
                'username' => 'thanaporn_cp',
                'password' => Hash::make('thana5599'),
                'fullname' => 'ธนพร จันทร์เพ็ญ',
                'phone' => '0946789015',
                'address' => '77 หมู่ 3 ต.ศีรษะจรเข้น้อย อ.บางเสาธง จ.สมุทรปราการ 10570',
                'bank_account' => '0589012367',
                'bust' => 84,
                'shoulder' => 35,
                'waist' => 64,
                'hips' => 91,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0016',
                'username' => 'nalinee_sw',
                'password' => Hash::make('nalin2026'),
                'fullname' => 'นลินี ศรีวงศ์',
                'phone' => '0957890126',
                'address' => '63/4 ถ.สุขุมวิท ต.แพรกษาใหม่ อ.เมือง จ.สมุทรปราการ 10280',
                'bank_account' => '0690123478',
                'bust' => 86,
                'shoulder' => 37,
                'waist' => 66,
                'hips' => 92,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0017',
                'username' => 'parichat_rw',
                'password' => Hash::make('pari1234'),
                'fullname' => 'ปาริชาติ รัตนวงศ์',
                'phone' => '0968901237',
                'address' => '29 หมู่ 7 ต.บางปู อ.เมือง จ.สมุทรปราการ 10280',
                'bank_account' => '0701234589',
                'bust' => 82,
                'shoulder' => 34,
                'waist' => 61,
                'hips' => 87,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0018',
                'username' => 'wipawadee_jt',
                'password' => Hash::make('wipa2026'),
                'fullname' => 'วิภาวดี จันทรา',
                'phone' => '0979012348',
                'address' => '5/2 ถ.เทพารักษ์ ต.ท้ายบ้านใหม่ อ.เมือง จ.สมุทรปราการ 10280',
                'bank_account' => '0812345690',
                'bust' => 88,
                'shoulder' => 38,
                'waist' => 68,
                'hips' => 94,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0019',
                'username' => 'sirikan_tk',
                'password' => Hash::make('siri5588'),
                'fullname' => 'สิริกัญญา ทองคำ',
                'phone' => '0980123459',
                'address' => '118 หมู่ 8 ต.คลองด่าน อ.บางบ่อ จ.สมุทรปราการ 10560',
                'bank_account' => '0923456701',
                'bust' => 85,
                'shoulder' => 36,
                'waist' => 64,
                'hips' => 92,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 'C0020',
                'username' => 'lalita_ks',
                'password' => Hash::make('lalita99'),
                'fullname' => 'ลลิตา เกษมสุข',
                'phone' => '0991234560',
                'address' => '36/8 ถ.ศรีนครินทร์ ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540',
                'bank_account' => '0034567812',
                'bust' => 83,
                'shoulder' => 35,
                'waist' => 63,
                'hips' => 90,
                'line_user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
