<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('orders')->insert([
            [
                'order_id' => 'O0001',
                'customer_id' => 'C0007',
                'item' => json_encode(['G001']),
                'event_date' => '2026-09-05',
                'pickup_date' => '2026-09-04',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-09-06',
                'return_time' => '18:00:00',
                'total_price' => 550.00,
                'deposit_prices' => 90.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0002',
                'customer_id' => 'C0001',
                'item' => json_encode(['W002']),
                'event_date' => '2026-09-10',
                'pickup_date' => '2026-09-08',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-09-12',
                'return_time' => '18:00:00',
                'total_price' => 650.00,
                'deposit_prices' => 100.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0003',
                'customer_id' => 'C0005',
                'item' => json_encode(['PT001']),
                'event_date' => '2026-09-12',
                'pickup_date' => '2026-09-12',
                'pickup_time' => '09:00:00',
                'return_date' => '2026-09-13',
                'return_time' => '20:00:00',
                'total_price' => 350.00,
                'deposit_prices' => 60.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0004',
                'customer_id' => 'C0007',
                'item' => json_encode(['PH003']),
                'event_date' => '2026-09-15',
                'pickup_date' => '2026-09-14',
                'pickup_time' => '11:00:00',
                'return_date' => '2026-09-17',
                'return_time' => '19:00:00',
                'total_price' => 550.00,
                'deposit_prices' => 90.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0005',
                'customer_id' => 'C0010',
                'item' => json_encode(['F002']),
                'event_date' => '2026-09-18',
                'pickup_date' => '2026-09-17',
                'pickup_time' => '09:00:00',
                'return_date' => '2026-09-20',
                'return_time' => '18:00:00',
                'total_price' => 500.00,
                'deposit_prices' => 80.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0006',
                'customer_id' => 'C0009',
                'item' => json_encode(['C003']),
                'event_date' => '2026-09-20',
                'pickup_date' => '2026-09-19',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-09-22',
                'return_time' => '18:00:00',
                'total_price' => 750.00,
                'deposit_prices' => 120.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0007',
                'customer_id' => 'C0002',
                'item' => json_encode(['G004']),
                'event_date' => '2026-09-22',
                'pickup_date' => '2026-09-21',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-09-26',
                'return_time' => '18:00:00',
                'total_price' => 550.00,
                'deposit_prices' => 90.00,
                'damage_price' => 100.00,
                'reject_reason' => 'คืนชุดล่าช้ากว่ากำหนด 2 วัน (กำหนดคืน 24 ก.ย. 69) หักค่าปรับจากเงินมัดจำ',
                'order_status' => 'overdue',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0008',
                'customer_id' => 'C0004',
                'item' => json_encode(['PH001']),
                'event_date' => '2026-09-25',
                'pickup_date' => '2026-09-24',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-09-28',
                'return_time' => '18:00:00',
                'total_price' => 650.00,
                'deposit_prices' => 100.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0009',
                'customer_id' => 'C0008',
                'item' => json_encode(['W004']),
                'event_date' => '2026-09-27',
                'pickup_date' => '2026-09-26',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-09-30',
                'return_time' => '18:00:00',
                'total_price' => 650.00,
                'deposit_prices' => 100.00,
                'damage_price' => 200.00,
                'reject_reason' => 'ชุดเปื้อนคราบเครื่องสำอางบริเวณคอเสื้อ หักเงินมัดจำและเรียกเก็บค่าเสียหายเพิ่มเติม',
                'order_status' => 'damaged',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0010',
                'customer_id' => 'C0006',
                'item' => json_encode(['PT004']),
                'event_date' => '2026-10-02',
                'pickup_date' => '2026-10-01',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-04',
                'return_time' => '18:00:00',
                'total_price' => 550.00,
                'deposit_prices' => 90.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0011',
                'customer_id' => 'C0003',
                'item' => json_encode(['F004']),
                'event_date' => '2026-10-05',
                'pickup_date' => '2026-10-04',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-08',
                'return_time' => '18:00:00',
                'total_price' => 700.00,
                'deposit_prices' => 110.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0012',
                'customer_id' => 'C0001',
                'item' => json_encode(['C005']),
                'event_date' => '2026-10-08',
                'pickup_date' => '2026-10-07',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-08',
                'return_time' => '18:00:00',
                'total_price' => 800.00,
                'deposit_prices' => 120.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0013',
                'customer_id' => 'C0005',
                'item' => json_encode(['PH002']),
                'event_date' => '2026-10-10',
                'pickup_date' => '2026-10-09',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-14',
                'return_time' => '18:00:00',
                'total_price' => 750.00,
                'deposit_prices' => 120.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0014',
                'customer_id' => 'C0010',
                'item' => json_encode(['G002']),
                'event_date' => '2026-10-12',
                'pickup_date' => '2026-10-11',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-14',
                'return_time' => '18:00:00',
                'total_price' => 600.00,
                'deposit_prices' => 90.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0015',
                'customer_id' => 'C0009',
                'item' => json_encode(['W001']),
                'event_date' => '2026-10-15',
                'pickup_date' => '2026-10-14',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-16',
                'return_time' => '18:00:00',
                'total_price' => 450.00,
                'deposit_prices' => 70.00,
                'damage_price' => 0.00,
                'reject_reason' => 'ลูกค้าแจ้งยกเลิกก่อนถึงวันรับชุด เนื่องจากเปลี่ยนแผนงานกะทันหัน',
                'order_status' => 'cancelled',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0016',
                'customer_id' => 'C0002',
                'item' => json_encode(['PT002']),
                'event_date' => '2026-10-18',
                'pickup_date' => '2026-10-17',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-19',
                'return_time' => '18:00:00',
                'total_price' => 450.00,
                'deposit_prices' => 70.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'confirmed',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0017',
                'customer_id' => 'C0004',
                'item' => json_encode(['C002']),
                'event_date' => '2026-10-20',
                'pickup_date' => '2026-10-19',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-24',
                'return_time' => '18:00:00',
                'total_price' => 700.00,
                'deposit_prices' => 110.00,
                'damage_price' => 150.00,
                'reject_reason' => 'คืนชุดล่าช้ากว่ากำหนด 3 วัน (กำหนดคืน 21 ต.ค. 69) มีการหักค่าปรับจากเงินมัดจำ',
                'order_status' => 'overdue',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'O0018',
                'customer_id' => 'C0008',
                'item' => json_encode(['PH004']),
                'event_date' => '2026-10-25',
                'pickup_date' => '2026-10-24',
                'pickup_time' => '10:00:00',
                'return_date' => '2026-10-28',
                'return_time' => '18:00:00',
                'total_price' => 650.00,
                'deposit_prices' => 100.00,
                'damage_price' => 0.00,
                'reject_reason' => null,
                'order_status' => 'pending',
                'slip_image' => null,
                'tracking_number' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
