<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ล้างข้อมูลเก่าก่อนลงใหม่ (เพื่อป้องกัน PK ซ้ำ)
        DB::table('products')->truncate();

        DB::table('products')->insert([
            [
                'product_id' => 'C001',
                'product_name' => 'ชุดนักผจญภัยสไตล์',
                'category' => 'costume',
                'size' => 'M',
                'description' => 'ชุดนักผจญภัยโทนสีน้ำตาลและครีม ประกอบด้วยเสื้อแขนยาวสีขาว คอร์เซ็ตสีน้ำตาลเข้ม กางเกงสไตล์คาร์โก้ และเข็มขัดพร้อมกระเป๋าเสริมดีเทล เพิ่มความโดดเด่นด้วยผ้าคลุมศีรษะและรองเท้าบูต ให้ลุคเท่ ลึกลับ และพร้อมออกเดินทางสู่โลกแฟนตาซี',
                'rental_fee' => 700.00,
                'deposit' => 110.00,
                'rental_duration_days' => 3,
                'status' => true,
                'image' => json_encode([
                'images/costume/C001/C001-1.jpeg',
                'images/costume/C001/C001-2.jpeg',
                'images/costume/C001/C001-3.jpeg',]),
                'review' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'C002',
                'product_name' => 'ชุดเจ้าหญิงรัตติกาล ',
                'category' => 'costume',
                'size' => 'L',
                'description' => 'ชุดเดรสกระโปรงยาวสีน้ำเงินเข้ม ตกแต่งด้วยลวดลายสีทองอันประณีต พร้อมเสื้อแขนยาวลูกไม้สีขาวและเครื่องประดับสไตล์วินเทจ ดีไซน์คอร์เซ็ตช่วยเน้นช่วงเอว เสริมด้วยกระโปรงระบายหลายชั้นที่พลิ้วไหวอย่างสง่างาม ให้ความรู้สึกราวกับเจ้าหญิงจากอาณาจักรแฟนตาซี
',
                'rental_fee' => 700.00,
                'deposit' => 110.00,
                'rental_duration_days' => 2,
                'status' => true,
                'image' => json_encode([
                'images/costume/C002/C002-1.jpeg',
                'images/costume/C002/C002-2.jpeg',
                'images/costume/C002/C002-3.jpeg']),
                'review' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
           [
                'product_id' => 'C003',
                'product_name' => 'ชุดหนูน้อยหมวกแดง',
                'category' => 'costume',
                'size' => 'L',
                'description' => 'ชุดหนูน้อยหมวกแดงในสไตล์โกธิก ประกอบด้วยผ้าคลุมมีฮู้ดสีแดงเข้ม เสื้อสีขาวแต่งขอบลูกไม้ คอร์เซ็ตสีดำผูกเชือกด้านหน้า และกระโปรงสีแดงดำหลายชั้นที่ให้ความพลิ้วไหว ผสมผสานความน่ารักจากเทพนิยายเข้ากับเสน่ห์อันลึกลับและน่าค้นหา',
                'rental_fee' => 750.00,
                'deposit' => 120.00,
                'rental_duration_days' => 3,
                'status' => true,
                'image' => json_encode([
                'images/costume/C003/C003-1.jpeg',
                'images/costume/C003/C003-2.jpeg',
                'images/costume/C003/C003-3.jpeg']),
                'review' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'C004',
                'product_name' => 'ชุดวิญญาณสีขาว',
                'category' => 'costume',
                'size' => 'XL',
                'description' => 'ชุดผ้าคลุมสีขาวยาวตั้งแต่ศีรษะจรดปลายเท้า โดดเด่นด้วยเนื้อผ้าที่ทิ้งตัวเป็นชั้นอย่างเป็นธรรมชาติ พร้อมช่องดวงตาสีดำที่ช่วยเพิ่มความลึกลับ ดีไซน์เรียบง่ายแต่สร้างบรรยากาศชวนขนลุกได้อย่างมีเอกลักษณ์ เหมาะสำหรับผู้ที่ต้องการลุคผีคลาสสิกที่สวมใส่ได้ง่าย',
                'rental_fee' => 600.00,
                'deposit' => 90.00,
                'rental_duration_days' => 4,
                'status' => true,
                'image' => json_encode([
                    'images/costume/C004/C004-1.jpeg',
                    'images/costume/C004/C004-2.jpeg',
                    'images/costume/C004/C004-3.jpeg',
                ]),
                'review' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
],
                [
                'product_id' => 'C005',
                'product_name' => 'ชุดภูตพฤกษา',
                'category' => 'costume',
                'size' => 'XL',
                'description' => 'ชุดแฟนตาซีที่ผสมผสานสีเขียวมะกอกและสีชมพูอ่อนอย่างลงตัว โดดเด่นด้วยคอร์เซ็ตสีเขียว กระโปรงตกแต่งลวดลายดอกไม้สีทอง และผ้าคลุมโปร่งแสงสีชมพูที่พลิ้วไหวรอบตัว เสริมด้วยรายละเอียดดอกไม้และเครื่องประดับบริเวณช่วงไหล่ ให้ลุคราวกับภูตสาวผู้พิทักษ์สวนดอกไม้ในดินแดนมหัศจรรย์
',
                'rental_fee' => 800.00,
                'deposit' => 120.00,
                'rental_duration_days' => 1,
                'status' => true,
                'image' => json_encode([
                    'images/costume/C005/C005-1.jpeg',
                    'images/costume/C005/C005-2.jpeg',
                    'images/costume/C005/C005-3.jpeg',
                ]),
                'review' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
                ],[
        'product_id' => 'F001',
        'product_name' => 'เสื้อคลุมสีงาช้าง',
        'category' => 'formal',
        'size' => 'L',
        'description' => 'เสื้อคลุมสีขาวงาช้างดีไซน์แขนยาวทรงกว้าง ตกแต่งกระดุมสีทองเรียงด้านหน้า เพิ่มความหรูหราและสง่างาม มาพร้อมกระเป๋าถือสีขาวลายควิลท์ที่ช่วยเติมเต็มลุคให้ดูสุภาพและมีระดับ เหมาะสำหรับผู้ที่ชื่นชอบแฟชั่นเรียบง่ายแต่โดดเด่น',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 2,
        'status' => true,
        'image' => json_encode([
            'images/formal/F001/F001-1.jpeg',
            'images/formal/F001/F001-2.jpeg',
            'images/formal/F001/F001-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'F002',
        'product_name' => 'เซตทำงานสีดำ',
        'category' => 'formal',
        'size' => 'S',
        'description' => 'เซตเสื้อเชิ้ตสีดำลายทางแนวตั้ง จับคู่กับกางเกงขายาวทรงขากว้างสีดำและเข็มขัดเรียบหรู เสริมลุคให้ดูมั่นใจ ทันสมัย และมีความเป็นมืออาชีพ เหมาะสำหรับวันที่ต้องการความคล่องตัวพร้อมภาพลักษณ์ที่ดูดี',
        'rental_fee' => 500.00,
        'deposit' => 80.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/formal/F002/F002-1.jpeg',
            'images/formal/F002/F002-2.jpeg',
            'images/formal/F002/F002-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'F003',
        'product_name' => 'เซตสูทกระโปรงสีชมพู',
        'category' => 'formal',
        'size' => 'M',
        'description' => 'เซตสูทสีชมพูอ่อนประกอบด้วยเสื้อเบลเซอร์กระดุมสองแถว จับคู่กับเสื้อด้านในสีขาวและกระโปรงยาวทรงพลิ้ว เพิ่มความอ่อนหวานด้วยโทนสีพาสเทล พร้อมดีไซน์ที่ดูสุภาพและสง่างาม ให้ลุคคุณหนูที่มีเสน่ห์และทันสมัย',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 2,
        'status' => true,
        'image' => json_encode([
            'images/formal/F003/F003-1.jpeg',
            'images/formal/F003/F003-2.jpeg',
            'images/formal/F003/F003-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'F004',
        'product_name' => 'เซตสูทสีน้ำตาลมอคค่า',
        'category' => 'formal',
        'size' => 'L',
        'description' => 'เซตสูทสีน้ำตาลมอคค่า ประกอบด้วยเสื้อเบลเซอร์ครอปทรงสวยและกางเกงขายาวทรงขากว้าง จับคู่กับเสื้อคอเต่าสีดำเพื่อเพิ่มมิติให้กับการแต่งกาย โทนสีน้ำตาลอบอุ่นช่วยสร้างลุคที่ดูเรียบเท่ มีระดับ และเหมาะกับแฟชั่นสไตล์มินิมอล',
        'rental_fee' => 700.00,
        'deposit' => 110.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/formal/F004/F004-1.jpeg',
            'images/formal/F004/F004-2.jpeg',
            'images/formal/F004/F004-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'F005',
        'product_name' => 'เซตเสื้อเขียวเสจ',
        'category' => 'formal',
        'size' => 'S',
        'description' => 'เซตเสื้อเชิ้ตสีเขียวเสจแขนยาว จับคู่กับกางเกงเอวสูงสีครีมทรงขากว้าง เพิ่มความสมดุลด้วยกระเป๋าถือสีเบจ ให้ลุคที่ดูสบายตา อ่อนโยน และมีความสุภาพในเวลาเดียวกัน เหมาะสำหรับผู้ที่ชื่นชอบการแต่งตัวโทนสีธรรมชาติ',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/formal/F005/F005-1.jpeg',
            'images/formal/F005/F005-2.jpeg',
            'images/formal/F005/F005-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'G001',
        'product_name' => 'ชุดราตรีสีงาช้าง',
        'category' => 'graduation',
        'size' => 'XL',
        'description' => 'ชุดเดรสยาวสีงาช้างเนื้อผ้าซาติน ดีไซน์เกาะอกพร้อมคอร์เซ็ตด้านหน้าและกระโปรงทรงสอบที่ช่วยเสริมความสง่างาม เพิ่มความโดดเด่นด้วยผ้าคลุมสีขาวขลิบขอบสีน้ำเงินและสีทอง ให้ลุคที่ดูภูมิฐาน เรียบหรู และมีเอกลักษณ์',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 2,
        'status' => true,
        'image' => json_encode([
            'images/graduation/G001/G001-1.jpeg',
            'images/graduation/G001/G001-2.jpeg',
            'images/graduation/G001/G001-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'G002',
        'product_name' => 'ชุดเดรสประดับมุก',
        'category' => 'graduation',
        'size' => 'XL',
        'description' => 'ชุดเดรสยาวสีแชมเปญอ่อน โดดเด่นด้วยช่วงอกประดับมุกและดีไซน์เปิดไหล่ที่ช่วยเพิ่มความอ่อนหวาน ตัวชุดเข้ารูปช่วงเอวและสะโพกอย่างสง่างาม เสริมด้วยผ้าคลุมสีขาวขลิบขอบน้ำเงินทอง เพิ่มความโดดเด่นให้ลุคดูหรูหราและน่าประทับใจ',
        'rental_fee' => 600.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/graduation/G002/G002-1.jpeg',
            'images/graduation/G002/G002-2.jpeg',
            'images/graduation/G002/G002-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'G003',
        'product_name' => 'ชุดลูกไม้สีขาว',
        'category' => 'graduation',
        'size' => 'L',
        'description' => 'ชุดเดรสยาวสีขาวตกแต่งด้วยผ้าลูกไม้ลายดอกไม้ทั่วทั้งตัว ช่วงอกดีไซน์เกาะอกพร้อมรายละเอียดผ้าจับจีบ เพิ่มความอ่อนหวานและมีมิติให้กับชุด กระโปรงทรงยาวช่วยเสริมลุคให้ดูเรียบร้อยและสง่างาม จับคู่กับผ้าคลุมขลิบสีน้ำเงินทองอย่างลงตัว',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/graduation/G003/G003-1.jpeg',
            'images/graduation/G003/G003-2.jpeg',
            'images/graduation/G003/G003-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'G004',
        'product_name' => 'ชุดคอร์เซ็ตกระโปรงพลีต',
        'category' => 'graduation',
        'size' => 'S',
        'description' => 'ชุดเดรสสีแชมเปญอ่อน โดดเด่นด้วยคอร์เซ็ตเข้ารูปที่ช่วยเน้นช่วงเอว จับคู่กับกระโปรงยาวจับจีบพลิ้วไหว เพิ่มความอ่อนช้อยและสง่างามให้กับทุกการเคลื่อนไหว พร้อมผ้าคลุมสีขาวขลิบสีน้ำเงินและทองที่ช่วยเติมเต็มลุคให้ดูภูมิฐานและโดดเด่น',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/graduation/G004/G004-1.jpeg',
            'images/graduation/G004/G004-2.jpeg',
            'images/graduation/G004/G004-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'G005',
        'product_name' => 'ชุดลูกไม้เจ้าหญิง',
        'category' => 'graduation',
        'size' => 'M',
        'description' => 'ชุดเดรสยาวสีขาวแต่งลูกไม้ลายดอกไม้ละเอียดทั่วทั้งตัว ดีไซน์ช่วงอกแบบคอร์เซ็ตพร้อมสายเดี่ยวและกระโปรงทรงยาวที่ช่วยสร้างความพลิ้วไหว เพิ่มความหรูหราด้วยผ้าคลุมสีขาวขลิบขอบน้ำเงินทอง ให้ลุคที่ดูอ่อนหวาน เรียบร้อย และสง่างามในเวลาเดียวกัน',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/graduation/G005/G005-1.jpeg',
            'images/graduation/G005/G005-2.jpeg',
            'images/graduation/G005/G005-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PT001',
        'product_name' => 'เดรสชีฟองลายดอกชมพูพริ้วสายคล้องคอ',
        'category' => 'party',
        'size' => 'M',
        'description' => 'ชุดเดรสสีขาวตกแต่งด้วยลายดอกกุหลาบสีแดงขนาดเล็ก ให้ความรู้สึกหวานและโรแมนติก ตัวเสื้อเป็นแบบคล้องคอและเข้ารูปบริเวณเอว ช่วยเน้นสัดส่วนให้ดูชัดเจน ส่วนกระโปรงเป็นทรงพองและมีการซ้อนชั้นของผ้า ทำให้ชุดดูมีวอลลุ่มและพลิ้วไหว จุดเด่นอีกอย่างคือชายผ้าที่ปล่อยยาวลงมาด้านข้าง ช่วยเพิ่มความน่าสนใจและให้กลิ่นอายแฟชั่นวินเทจ',
        'rental_fee' => 350.00,
        'deposit' => 60.00,
        'rental_duration_days' => 1,
        'status' => true,
        'image' => json_encode([
            'images/party/PT001/PT001-1.jpeg',
            'images/party/PT001/PT001-2.jpeg',
            'images/party/PT001/PT001-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PT002',
        'product_name' => 'เซ็ตเดรสลูกไม้ลายดอกแดง+เสื้อคลุมคาร์ดิแกน',
        'category' => 'party',
        'size' => 'L',
        'description' => 'เดรสสีครีมลายดอกไม้เล็ก ๆ โทนเหลืองและน้ำตาล ให้ความรู้สึกอบอุ่นและเป็นธรรมชาติ ตัวเสื้อเข้ารูปบริเวณช่วงอกและเอว พร้อมสายผูกเป็นโบว์บริเวณไหล่ เพิ่มความน่ารักและความเป็นผู้หญิง กระโปรงเป็นทรงบานพลิ้ว เนื้อผ้าบางและโปร่ง ทำให้ชุดดูเบาสบายและเหมือนการนำบรรยากาศของสวนดอกไม้มาถ่ายทอดผ่านเสื้อผ้า',
        'rental_fee' => 450.00,
        'deposit' => 70.00,
        'rental_duration_days' => 2,
        'status' => true,
        'image' => json_encode([
            'images/party/PT002/PT002-1.jpeg',
            'images/party/PT002/PT002-2.jpeg',
            'images/party/PT002/PT002-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PT003',
        'product_name' => 'เซ็ตเดรสระบายชั้นๆ ลายดอกสีฟ้า+เสื้อคลุมไหมพรม',
        'category' => 'party',
        'size' => 'L',
        'description' => 'เดรสสีขาวที่ใช้ลวดลายดอกไม้สีดำเป็นองค์ประกอบหลัก ทำให้เกิดความโดดเด่นจากการตัดกันของสีขาวและดำ ตัวชุดมีดีไซน์เข้ารูปบริเวณเอวและกระโปรงบาน ช่วยสร้างรูปทรงให้ดูสง่างาม จุดเด่นคือผ้าชีฟองสีดำขนาดใหญ่บริเวณไหล่ที่ผูกเป็นโบว์และปล่อยชายยาวลงมา ทำให้ชุดมีความหรูหราและมีเอกลักษณ์มากขึ้น',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/party/PT003/PT003-1.jpeg',
            'images/party/PT003/PT003-2.jpeg',
            'images/party/PT003/PT003-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PT004',
        'product_name' => 'เดรสลายเชอร์รี่ขอบสก็อตแดงสไตล์คอทเทจ',
        'category' => 'party',
        'size' => 'M',
        'description' => 'เดรสสีไวน์แดงเข้มที่มีประกายระยิบระยับทั่วทั้งชุด ให้ความรู้สึกหรูหราและเหมาะกับงานกลางคืน ตัวชุดเป็นแบบคล้องคอและมีการจับเดรปบริเวณช่วงอกและเอว ช่วยเน้นรูปร่างให้ดูโดดเด่น บริเวณสะโพกประดับด้วยเครื่องประดับสีเงิน เพิ่มความหรูหราให้กับชุด ส่วนกระโปรงเป็นแบบระบายหลายชั้นและมีชายผ้าทิ้งตัวลงมา ทำให้เกิดการเคลื่อนไหวที่ดูพลิ้วและมีเสน่ห์',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/party/PT004/PT004-1.jpeg',
            'images/party/PT004/PT004-2.jpeg',
            'images/party/PT004/PT004-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PT005',
        'product_name' => 'เดรสชีฟองลายดอกชมพูระบายสองชั้น',
        'category' => 'party',
        'size' => 'M',
        'description' => 'ชุดเดรสสีดำที่ตกแต่งด้วยลายประกายเล็ก ๆ ให้ความรู้สึกลึกลับ หรูหรา และโดดเด่น ตัวชุดเป็นแบบคล้องคอและเข้ารูปตามสรีระ ช่วงเอวมีการจับจีบของผ้าเพื่อเน้นรูปร่างให้ดูชัดเจนขึ้น ส่วนกระโปรงเป็นทรงไม่สมมาตร มีระบายหลายชั้นและชายผ้าที่ยาวลงมาทั้งสองด้าน ช่วยเพิ่มความพลิ้วไหวและความโดดเด่นให้กับชุด',
        'rental_fee' => 450.00,
        'deposit' => 70.00,
        'rental_duration_days' => 2,
        'status' => true,
        'image' => json_encode([
            'images/party/PT005/PT005-1.jpeg',
            'images/party/PT005/PT005-2.jpeg',
            'images/party/PT005/PT005-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PH001',
        'product_name' => 'เดรสชีฟองลายดอกชมพูพริ้วสายคล้องคอ',
        'category' => 'photoshoot',
        'size' => 'L',
        'description' => 'มินิเดรสลายดอกไม้เล็กๆ โทนสีชมพูหวานละมุน ออกแบบคอเหลี่ยมพร้อมดีเทลสายคล้องคอผูกโบว์ ช่วงอกจับย่นช่วยเสริมทรง แขนยาวทรงกระดิ่งพริ้วๆ ผ้าชีฟองเนื้อเบาสบาย ให้ลุคสาวหวานสไตล์วินเทจโรแมนติก',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/photoshoot/PH001/PH001-1.jpeg',
            'images/photoshoot/PH001/PH001-2.jpeg',
            'images/photoshoot/PH001/PH001-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PH002',
        'product_name' => 'เซ็ตเดรสลูกไม้ลายดอกแดง+เสื้อคลุมคาร์ดิแกน',
        'category' => 'photoshoot',
        'size' => 'S',
        'description' => 'มินิเดรสสไตล์ลอลิต้าลายดอกไม้สีแดงบนพื้นสีครีม ตกแต่งด้วยชายระบายลูกไม้สีขาวและโบว์สีแดงสุดน่ารัก แมตช์คู่กับเสื้อคาดิแกนแขนยาวสีแดงเข้าชุดกัน ให้ลุคคุณหนูสุดคาวาอี้ อบอุ่นและสดใส',
        'rental_fee' => 750.00,
        'deposit' => 120.00,
        'rental_duration_days' => 5,
        'status' => true,
        'image' => json_encode([
            'images/photoshoot/PH002/PH002-1.jpeg',
            'images/photoshoot/PH002/PH002-2.jpeg',
            'images/photoshoot/PH002/PH002-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PH003',
        'product_name' => 'เซ็ตเดรสระบายชั้นๆ ลายดอกสีฟ้า+เสื้อคลุมไหมพรม',
        'category' => 'photoshoot',
        'size' => 'XL',
        'description' => 'มินิเดรสสายเดี่ยวลายดอกไม้สีฟ้าสดใส ช่วงอกแต่งรายละเอียดเชือกร้อยผูกโบว์ กระโปรงระบายเป็นชั้นๆ (Tiered skirt) ให้ความพริ้วไหว สวมทับด้วยเสื้อคลุมไหมพรมคาร์ดิแกนสีฟ้าพาสเทลเข้ากัน ให้ลุคละมุน น่ารัก น่าทะนุถนอม',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/photoshoot/PH003/PH003-1.jpeg',
            'images/photoshoot/PH003/PH003-2.jpeg',
            'images/photoshoot/PH003/PH003-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PH004',
        'product_name' => 'เดรสลายเชอร์รี่ขอบสก็อตแดงสไตล์คอทเทจ',
        'category' => 'photoshoot',
        'size' => 'XL',
        'description' => 'มินิเดรสสไตล์คอทเทจคอร์สุดสดใส ตัวชุดเป็นผ้าสีครีมสกรีนลายเชอร์รี่เล็กๆ ตกแต่งโบว์และลายสก็อตสีแดงบริเวณอก แขนเสื้อ และชายกระโปรง แมตช์กับถุงเท้าขอยาวแต่งลูกไม้และรองเท้าส้นตึก ให้ลุคสาวน้อยขี้เล่น น่ารักวิกฤต',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/photoshoot/PH004/PH004-1.jpeg',
            'images/photoshoot/PH004/PH004-2.jpeg',
            'images/photoshoot/PH004/PH004-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'PH005',
        'product_name' => 'เดรสชีฟองลายดอกชมพูระบายสองชั้น',
        'category' => 'photoshoot',
        'size' => 'L',
        'description' => 'มินิเดรสผ้าชีฟองลายดอกไม้สีชมพูละมุนตา แขนยาวทรงพองแต่งระบายที่ปลายแขน คอเหลี่ยมแต่งสายผูกโบว์หน้าอก กระโปรงบานพริ้ว 2 ชั้น ให้ความรู้สึกละมุน หวานซ่อนเสน่ห์สไตล์ลูกคุณหนูไปเที่ยวคาเฟ่',
        'rental_fee' => 550.00,
        'deposit' => 90.00,
        'rental_duration_days' => 3,
        'status' => true,
        'image' => json_encode([
            'images/photoshoot/PH005/PH005-1.jpeg',
            'images/photoshoot/PH005/PH005-2.jpeg',
            'images/photoshoot/PH005/PH005-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'W001',
        'product_name' => 'คริสตัลประกายเพชรพร้อมผ้าคลุมไหล่ยาว',
        'category' => 'weding',
        'size' => 'S',
        'description' => 'ชุดแต่งงานทรงเอไลน์ปักปักเลื่อมและคริสตัลระยิบระยับทั่วทั้งตัว ตัวเสื้อช่วงอกเว้าลึกทรงวีคอร์เซ็ท โดดเด่นด้วยเสื้อคลุมไหล่ยาวลากพื้น ปักลายลูกไม้อย่างปราณีต ให้ลุคดูสง่างามดั่งนางพญาและมีเสน่ห์ลึกลับ',
        'rental_fee' => 450.00,
        'deposit' => 70.00,
        'rental_duration_days' => 2,
        'status' => true,
        'image' => json_encode([
            'images/weding/W001/W001-1.jpeg',
            'images/weding/W001/W001-2.jpeg',
            'images/weding/W001/W001-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'W002',
        'product_name' => 'ผ้าตาข่ายปักลูกไม้ฝรั่งเศสสีแชมเปญ',
        'category' => 'weding',
        'size' => 'M',
        'description' => 'ชุดแต่งงานโทนสีครีมแชมเปญสไตล์คลาสสิก ช่วงบนเป็นผ้าตาข่ายซีทรูแต่งดีเทลลูกไม้ฝรั่งเศสลวดลายอ่อนช้อย ตัวกระโปรงเป็นผ้าชีฟองพริ้วไหว ซ้อนทับด้วยชั้นลูกไม้ฉลุชายล่าง ให้ความรู้สึกอ่อนหวาน สง่างาม และเรียบหรูสไตล์ยุโรป',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/weding/W002/W002-1.jpeg',
            'images/weding/W002/W002-2.jpeg',
            'images/weding/W002/W002-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'W003',
        'product_name' => 'เมอร์เมดคอสูงคอร์เซ็ทสไตล์เทพธิดา',
        'category' => 'weding',
        'size' => 'L',
        'description' => 'ชุดแต่งงานทรงหางปลา เน้นสัดส่วนโค้งเว้าอย่างเด่นชัด ช่วงคอเป็นทรงคอสูง ตกแต่งสร้อยคริสตัลและคอร์เซ็ทกระชับเอว แขนเสื้อยาวผ้ามัสลินพริ้วสไตล์เอลฟ์/เทพธิดา ตัวผ้าตึงจับเดรปอย่างพิถีพิถัน ให้ลุคสุดแกลม งดงามดั่งเทพนิทาน',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/weding/W003/W003-1.jpeg',
            'images/weding/W003/W003-2.jpeg',
            'images/weding/W003/W003-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'W004',
        'product_name' => 'ทรงเอไลน์ปักดอกไม้ 3 มิติสีไอวอรี่',
        'category' => 'weding',
        'size' => 'S',
        'description' => 'ชุดแต่งงานทรงเอไลน์สีไอวอรี่ ปักปีกดอกไม้ 3 มิติและลูกไม้วินเทจกระจายทั่วทั้งชุดอย่างวิจิตร ช่วงคอและไหล่ใช้ผ้าซีทรูเนียนไปกับผิว ให้ลุคที่นุ่มนวล หวานละมุน โรแมนติก และดูบริสุทธิ์ดั่งเจ้าหญิงในสวนดอกไม้',
        'rental_fee' => 650.00,
        'dep osit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/weding/W004/W004-1.jpeg',
            'images/weding/W004/W004-2.jpeg',
            'images/weding/W004/W004-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'W005',
        'product_name' => 'ทรงบอลกาวน์เปิดไหล่ปักดอกไม้นูน 3 มิติ',
        'category' => 'weding',
        'size' => 'XL',
        'description' => 'ชุดแต่งงานทรงบอลกาวน์ สุดอลังการ ดีไซน์เปิดไหล่ พร้อมสายแขนผ้าชีฟองปล่อยยาว คอร์เซ็ทเน้นเอวคอดปักประดับด้วยดอกไม้ปั๊มนูนและงานลูกไม้ละเอียด ตัวกระโปรงแหวกซ้อนชั้นเพิ่มมิติความพริ้วไหว ให้ลุคเจ้าหญิงผู้สูงศักดิ์ในเทพนิยาย',
        'rental_fee' => 650.00,
        'deposit' => 100.00,
        'rental_duration_days' => 4,
        'status' => true,
        'image' => json_encode([
            'images/weding/W005/W005-1.jpeg',
            'images/weding/W005/W005-2.jpeg',
            'images/weding/W005/W005-3.jpeg',
        ]),
        'review' => json_encode([]),
        'created_at' => now(),
        'updated_at' => now(),
    ],




        ]);
    }
}